-- Split-Guardian Supabase Schema

-- Drop tables if they exist to apply fresh schema (WARNING: Drops data)
DROP TABLE IF EXISTS trade_log;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS split_type;

CREATE TYPE split_type AS ENUM ('forward', 'reverse');

-- Users Table (Combines profiles, settings, and oauth tokens)
CREATE TABLE users (
  user_email text primary key,
  alpaca_access_token text,
  alpaca_account_id text,
  allow_reverse_splits boolean default false not null,
  trade_size_dollars numeric default 100 not null,
  position_type text default 'quantity' not null,
  is_auto_buy_enabled boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trade Log Table
CREATE TABLE trade_log (
  id bigint generated by default as identity primary key,
  user_email text not null references users(user_email) on delete cascade,
  ticker text not null,
  split_ratio text not null,
  sources text[] default '{}' not null,
  split_type split_type not null,
  execution_status text not null,
  retry_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
