-- Split-Guardian Supabase Schema

CREATE TYPE split_type AS ENUM ('forward', 'reverse');

-- Trade Log Table
CREATE TABLE trade_log (
  id bigint generated by default as identity primary key,
  ticker text not null,
  split_ratio text not null,
  source_site text not null,
  split_type split_type not null,
  execution_status text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Settings Table
CREATE TABLE settings (
  id bigint generated by default as identity primary key,
  allow_reverse_splits boolean default false not null,
  trade_size_dollars numeric default 100 not null,
  is_auto_buy_enabled boolean default true not null
);

-- Insert Default Settings
INSERT INTO settings (id, allow_reverse_splits, trade_size_dollars, is_auto_buy_enabled) 
VALUES (1, false, 100, true);
